<a href="https://colab.research.google.com/github/Machine-Learning-Visao-Computacional-T1/CodigosDeAula-Python-Dados-/blob/main/Modulo2/Semana4/lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_wine # Base nativa do Python

print("="*60)
print("CORREÇÃO DO LAB 2: INDÚSTRIA QUÍMICA (MULTICLASSE)")
print("="*60)

# 1. IMPORTAÇÃO DOS DADOS
dados_quimicos = load_wine()
X_dados = dados_quimicos.data   # 13 sensores químicos
Y_dados = dados_quimicos.target # Classes 0, 1 e 2
nomes_classes = dados_quimicos.target_names

print(f"Total de Bebidas: {len(X_dados)}")
print(f"Categorias: {len(nomes_classes)} ({nomes_classes[0]}, {nomes_classes[1]}, {nomes_classes[2]})")

CORREÇÃO DO LAB 2: INDÚSTRIA QUÍMICA (MULTICLASSE)
Total de Bebidas: 178
Categorias: 3 (class_0, class_1, class_2)


In [2]:
print(X_dados)

[[1.423e+01 1.710e+00 2.430e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [1.327e+01 4.280e+00 2.260e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [1.317e+01 2.590e+00 2.370e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [1.413e+01 4.100e+00 2.740e+00 ... 6.100e-01 1.600e+00 5.600e+02]]


In [3]:
np.unique(Y_dados, return_counts=True)

(array([0, 1, 2]), array([59, 71, 48]))