<a href="https://colab.research.google.com/github/Machine-Learning-Visao-Computacional-T1/CodigosDeAula-Python-Dados-/blob/main/Semana3/ML_Exemplo_Completo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# 1. IMPORTANDO AS FERRAMENTAS
import numpy as np
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

In [4]:
print("--- 1. CARREGANDO E MANIPULANDO DADOS (A Lógica em Ação) ---")
dataset = load_wine()
X_bruto = dataset.data   # As características dos vinhos (Álcool, Cor, etc)
y_bruto = dataset.target # A classe do vinho (0, 1 ou 2)

print("\n1. Primeiras 5 linhas do X_bruto (Características):")
# O [:5] diz: "pegue do início até o índice 4"
print(X_bruto[:5])

# Printando os 5 primeiros alvos (y)
print("\n2. Primeiros 5 labels do y_bruto (Gabarito Real):")
print(y_bruto[:5])

--- 1. CARREGANDO E MANIPULANDO DADOS (A Lógica em Ação) ---

1. Primeiras 5 linhas do X_bruto (Características):
[[1.423e+01 1.710e+00 2.430e+00 1.560e+01 1.270e+02 2.800e+00 3.060e+00
  2.800e-01 2.290e+00 5.640e+00 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 1.120e+01 1.000e+02 2.650e+00 2.760e+00
  2.600e-01 1.280e+00 4.380e+00 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 1.860e+01 1.010e+02 2.800e+00 3.240e+00
  3.000e-01 2.810e+00 5.680e+00 1.030e+00 3.170e+00 1.185e+03]
 [1.437e+01 1.950e+00 2.500e+00 1.680e+01 1.130e+02 3.850e+00 3.490e+00
  2.400e-01 2.180e+00 7.800e+00 8.600e-01 3.450e+00 1.480e+03]
 [1.324e+01 2.590e+00 2.870e+00 2.100e+01 1.180e+02 2.800e+00 2.690e+00
  3.900e-01 1.820e+00 4.320e+00 1.040e+00 2.930e+00 7.350e+02]]

2. Primeiros 5 labels do y_bruto (Gabarito Real):
[0 0 0 0 0]


In [5]:
print("--- EXIBINDO O 'HEAD' COMPLETO (10 PRIMEIROS EXEMPLOS) ---")

# 1. Pegamos todos os nomes das colunas
nomes_colunas = dataset.feature_names

# 2. Criamos o cabeçalho juntando os nomes com uma barra vertical
# Usamos o .upper() para dar destaque, como vimos em Strings!
cabecalho = " | ".join([nome.upper() for nome in nomes_colunas]) + " | [CLASSE]"
print(cabecalho)
print("-" * len(cabecalho)) # Cria uma linha do tamanho exato do cabeçalho

# 3. Loop para os 10 primeiros exemplos
for i in range(10):
    # Usamos List Comprehension para arredondar cada número para 2 casas decimais
    # Isso evita que a tabela fique desalinhada com números gigantes
    linha_formatada = [f"{valor:.2d}" if isinstance(valor, int) else f"{valor:.2f}" for valor in X_bruto[i]]

    # Juntamos os valores formatados e printamos com a classe no final
    print(" | ".join(linha_formatada) + f" | {y_bruto[i]}")

--- EXIBINDO O 'HEAD' COMPLETO (10 PRIMEIROS EXEMPLOS) ---
ALCOHOL | MALIC_ACID | ASH | ALCALINITY_OF_ASH | MAGNESIUM | TOTAL_PHENOLS | FLAVANOIDS | NONFLAVANOID_PHENOLS | PROANTHOCYANINS | COLOR_INTENSITY | HUE | OD280/OD315_OF_DILUTED_WINES | PROLINE | [CLASSE]
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
14.23 | 1.71 | 2.43 | 15.60 | 127.00 | 2.80 | 3.06 | 0.28 | 2.29 | 5.64 | 1.04 | 3.92 | 1065.00 | 0
13.20 | 1.78 | 2.14 | 11.20 | 100.00 | 2.65 | 2.76 | 0.26 | 1.28 | 4.38 | 1.05 | 3.40 | 1050.00 | 0
13.16 | 2.36 | 2.67 | 18.60 | 101.00 | 2.80 | 3.24 | 0.30 | 2.81 | 5.68 | 1.03 | 3.17 | 1185.00 | 0
14.37 | 1.95 | 2.50 | 16.80 | 113.00 | 3.85 | 3.49 | 0.24 | 2.18 | 7.80 | 0.86 | 3.45 | 1480.00 | 0
13.24 | 2.59 | 2.87 | 21.00 | 118.00 | 2.80 | 2.69 | 0.39 | 1.82 | 4.32 | 1.04 | 2.93 | 735.00 | 0
14.20 | 1.76 | 2.45 | 15.20 | 11

In [6]:
print(dataset['DESCR'])

.. _wine_dataset:

Wine recognition dataset
------------------------

**Data Set Characteristics:**

:Number of Instances: 178
:Number of Attributes: 13 numeric, predictive attributes and the class
:Attribute Information:
    - Alcohol
    - Malic acid
    - Ash
    - Alcalinity of ash
    - Magnesium
    - Total phenols
    - Flavanoids
    - Nonflavanoid phenols
    - Proanthocyanins
    - Color intensity
    - Hue
    - OD280/OD315 of diluted wines
    - Proline
    - class:
        - class_0
        - class_1
        - class_2

:Summary Statistics:

============================= ==== ===== ======= =====
                                Min   Max   Mean     SD
============================= ==== ===== ======= =====
Alcohol:                      11.0  14.8    13.0   0.8
Malic Acid:                   0.74  5.80    2.34  1.12
Ash:                          1.36  3.23    2.36  0.27
Alcalinity of Ash:            10.6  30.0    19.5   3.3
Magnesium:                    70.0 162.0    99.7  14.3

In [8]:
# a) Usando List Comprehension e Condicionais para binarizar o alvo:
# Se for o vinho tipo 0, será classe 1 (Premium). O resto será 0 (Padrão).
y_processado = np.array([1 if classe == 0 else 0 for classe in y_bruto])

In [7]:
# b) Engenharia de Atributos com Laço FOR e IF/ELSE!
# Vamos criar uma nova coluna: "Teor Alcoólico Alto" (1 para Sim, 0 para Não)
# O nível de Álcool é a coluna de índice 0 no X_bruto.
X_novo = []
for linha in X_bruto:
    teor_alcool = linha[0]

    if teor_alcool >= 13.5:
        flag_alcool_alto = 1
    else:
        flag_alcool_alto = 0

    # Transformamos a linha em lista, adicionamos a nova coluna e guardamos
    linha_lista = list(linha)
    linha_lista.append(flag_alcool_alto)
    X_novo.append(linha_lista)

In [9]:
# Convertendo de volta para Array do NumPy (Acelerador matemático)
X_processado = np.array(X_novo)

print(f"Dados originais: {X_bruto.shape[1]} colunas.")
print(f"Dados processados: {X_processado.shape[1]} colunas (Nova coluna foi adicionada!).\n")

Dados originais: 13 colunas.
Dados processados: 14 colunas (Nova coluna foi adicionada!).



In [10]:
print(X_processado[:5])

[[1.423e+01 1.710e+00 2.430e+00 1.560e+01 1.270e+02 2.800e+00 3.060e+00
  2.800e-01 2.290e+00 5.640e+00 1.040e+00 3.920e+00 1.065e+03 1.000e+00]
 [1.320e+01 1.780e+00 2.140e+00 1.120e+01 1.000e+02 2.650e+00 2.760e+00
  2.600e-01 1.280e+00 4.380e+00 1.050e+00 3.400e+00 1.050e+03 0.000e+00]
 [1.316e+01 2.360e+00 2.670e+00 1.860e+01 1.010e+02 2.800e+00 3.240e+00
  3.000e-01 2.810e+00 5.680e+00 1.030e+00 3.170e+00 1.185e+03 0.000e+00]
 [1.437e+01 1.950e+00 2.500e+00 1.680e+01 1.130e+02 3.850e+00 3.490e+00
  2.400e-01 2.180e+00 7.800e+00 8.600e-01 3.450e+00 1.480e+03 1.000e+00]
 [1.324e+01 2.590e+00 2.870e+00 2.100e+01 1.180e+02 2.800e+00 2.690e+00
  3.900e-01 1.820e+00 4.320e+00 1.040e+00 2.930e+00 7.350e+02 0.000e+00]]


In [11]:
print(y_processado[:5])

[1 1 1 1 1]


In [12]:
print("--- O DATASET PROCESSADO ---")

# 1. Pegamos os nomes originais do dataset
nomes_colunas = list(dataset.feature_names)

# 2. ADICIONAMOS A NOSSA NOVA COLUNA NO FINAL DA LISTA DE NOMES!
nomes_colunas.append("teor_alcool_alto")

# 3. Criamos o cabeçalho atualizado
cabecalho = " | ".join([nome.upper() for nome in nomes_colunas]) + " | [CLASSE_BINARIA]"
print(cabecalho)
print("-" * len(cabecalho)) # Cria a linha divisória do tamanho exato

# 4. Loop para os 10 primeiros exemplos usando os dados NOVOS
for i in range(10):
    # Usamos List Comprehension para formatar os valores de X_processado
    # Como a nossa nova coluna é 0 ou 1, podemos deixá-la visualmente mais limpa
    linha_formatada = [f"{int(valor)}" if j == 13 else f"{valor:.2f}" for j, valor in enumerate(X_processado[i])]

    # Juntamos tudo e printamos com o novo gabarito (y_processado) no final
    print(" | ".join(linha_formatada) + f" | {y_processado[i]}")

--- O DATASET PROCESSADO ---
ALCOHOL | MALIC_ACID | ASH | ALCALINITY_OF_ASH | MAGNESIUM | TOTAL_PHENOLS | FLAVANOIDS | NONFLAVANOID_PHENOLS | PROANTHOCYANINS | COLOR_INTENSITY | HUE | OD280/OD315_OF_DILUTED_WINES | PROLINE | TEOR_ALCOOL_ALTO | [CLASSE_BINARIA]
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
14.23 | 1.71 | 2.43 | 15.60 | 127.00 | 2.80 | 3.06 | 0.28 | 2.29 | 5.64 | 1.04 | 3.92 | 1065.00 | 1 | 1
13.20 | 1.78 | 2.14 | 11.20 | 100.00 | 2.65 | 2.76 | 0.26 | 1.28 | 4.38 | 1.05 | 3.40 | 1050.00 | 0 | 1
13.16 | 2.36 | 2.67 | 18.60 | 101.00 | 2.80 | 3.24 | 0.30 | 2.81 | 5.68 | 1.03 | 3.17 | 1185.00 | 0 | 1
14.37 | 1.95 | 2.50 | 16.80 | 113.00 | 3.85 | 3.49 | 0.24 | 2.18 | 7.80 | 0.86 | 3.45 | 1480.00 | 1 | 1
13.24 | 2.59 | 2.87 | 21.00 | 118.00 | 2.80 | 2.69 | 0.39 | 1.82 | 4.32 | 1.04 | 2.93 | 735

In [13]:
print("--- 2. SEPARANDO TREINO E TESTE ---")
# Separamos 30% dos dados para testar a IA depois de treinada (para ela não "decorar" as respostas)
X_treino, X_teste, y_treino, y_teste = train_test_split(X_processado, y_processado, test_size=0.90, random_state=42)
print(f"Vinhos para Treinar a IA: {len(X_treino)}")
print(f"Vinhos para Testar a IA: {len(X_teste)}\n")


# Na etapa 2, mude o test_size de 0.30 para 0.90:
# X_treino, X_teste, y_treino, y_teste = train_test_split(X_processado, y_processado, test_size=0.90, random_state=42)

--- 2. SEPARANDO TREINO E TESTE ---
Vinhos para Treinar a IA: 124
Vinhos para Testar a IA: 54



In [14]:
print("--- 3. TREINANDO O MODELO (A Mágica) ---")
# Escolhemos o Algoritmo "Floresta Aleatória"
modelo_ia = RandomForestClassifier(random_state=42)
modelo_ia.fit(X_treino, y_treino) # O comando FIT é a IA aprendendo!
print("Inteligência Artificial treinada com sucesso!\n")


# Na etapa 3, treine a IA cortando a última coluna (nossa engenharia de atributos)
# O comando [:, :-1] significa "pegue todas as linhas, mas remova a última coluna"
#modelo_ia.fit(X_treino[:, :-1], y_treino)

# Na etapa 4, corte a última coluna na hora da previsão também:
#previsoes = modelo_ia.predict(X_teste[:, :-1])

--- 3. TREINANDO O MODELO (A Mágica) ---
Inteligência Artificial treinada com sucesso!



In [16]:
print("--- 4. FAZENDO PREVISÕES (Predict) ---")
# Pedimos para a IA prever as respostas baseada apenas nas características do X_teste
previsoes = modelo_ia.predict(X_teste)

--- 4. FAZENDO PREVISÕES (Predict) ---


In [17]:
print("--- 5. AVALIANDO O DESEMPENHO (Métricas) ---")
# Comparamos as previsões da IA com o gabarito real (y_teste)
acuracia = accuracy_score(y_teste, previsoes)
precisao = precision_score(y_teste, previsoes)
recall = recall_score(y_teste, previsoes)
f1 = f1_score(y_teste, previsoes)

--- 5. AVALIANDO O DESEMPENHO (Métricas) ---


In [18]:
print(f"🎯 Acurácia: {acuracia * 100:.2f}%")
print(f"🎯 Precisão: {precisao * 100:.2f}%")
print(f"🎯 Recall:   {recall * 100:.2f}%")
print(f"🎯 F1-Score: {f1 * 100:.2f}%\n")

🎯 Acurácia: 100.00%
🎯 Precisão: 100.00%
🎯 Recall:   100.00%
🎯 F1-Score: 100.00%



In [19]:
print("--- 6. MATRIZ DE CONFUSÃO ---")
matriz = confusion_matrix(y_teste, previsoes)
print(matriz)
print("\nLegenda da Matriz:")
print("[ Verdadeiros Negativos (VN)  |  Falsos Positivos (FP) ]")
print("[ Falsos Negativos (FN)       |  Verdadeiros Positivos (VP) ]")

--- 6. MATRIZ DE CONFUSÃO ---
[[35  0]
 [ 0 19]]

Legenda da Matriz:
[ Verdadeiros Negativos (VN)  |  Falsos Positivos (FP) ]
[ Falsos Negativos (FN)       |  Verdadeiros Positivos (VP) ]


In [20]:
from sklearn.metrics import classification_report, confusion_matrix

print("--- 5. RELATÓRIO DE CLASSIFICAÇÃO  ---")
# O target_names substitui os números 0 e 1 por textos para ficar mais legível
relatorio = classification_report(y_teste, previsoes, target_names=['Vinho Padrão (0)', 'Vinho Premium (1)'])
print(relatorio)

print("--- 6. MATRIZ DE CONFUSÃO ---")
matriz = confusion_matrix(y_teste, previsoes)
print(matriz)

--- 5. RELATÓRIO DE CLASSIFICAÇÃO  ---
                   precision    recall  f1-score   support

 Vinho Padrão (0)       1.00      1.00      1.00        35
Vinho Premium (1)       1.00      1.00      1.00        19

         accuracy                           1.00        54
        macro avg       1.00      1.00      1.00        54
     weighted avg       1.00      1.00      1.00        54

--- 6. MATRIZ DE CONFUSÃO ---
[[35  0]
 [ 0 19]]


In [23]:
from sklearn.model_selection import cross_val_score

print("--- VALIDAÇÃO CRUZADA ---")

# rodar o modelo 5 vezes, trocando quem é treino e quem é teste!

notas_validacao = cross_val_score(modelo_ia, X_processado, y_processado, cv=5)

print(f"Notas de acurácia em cada uma das 5 rodadas: {notas_validacao}")
print(f"Média Final de Acertos: {notas_validacao.mean() * 100:.2f}%")
print(f"Margem de Erro (Desvio Padrão): ±{notas_validacao.std() * 100:.2f}%\n")

print("--- (Feature Importance) ---")
# Vamos ver quais colunas ela achou mais importantes para tomar a decisão
importancias = modelo_ia.feature_importances_

# Pegamos os nomes originais e adicionamos a nossa coluna
nomes_completos = list(dataset.feature_names)
nomes_completos.append("teor_alcool_alto")

# Mostrando o Top 3 características mais usadas
print("Top 3 Regras que a IA usou para separar os vinhos:")
dicionario_importancias = dict(zip(nomes_completos, importancias))
top_3 = sorted(dicionario_importancias.items(), key=lambda x: x[1], reverse=True)[:3]

for nome, valor in top_3:
    print(f"- {nome.upper()}: {valor * 100:.1f}% de importância")

--- VALIDAÇÃO CRUZADA ---
Notas de acurácia em cada uma das 5 rodadas: [0.97222222 0.97222222 1.         0.97142857 1.        ]
Média Final de Acertos: 98.32%
Margem de Erro (Desvio Padrão): ±1.37%

--- (Feature Importance) ---
Top 3 Regras que a IA usou para separar os vinhos:
- PROLINE: 23.0% de importância
- ALCOHOL: 15.1% de importância
- FLAVANOIDS: 14.5% de importância
