<a href="https://colab.research.google.com/github/Machine-Learning-Visao-Computacional-T1/CodigosDeAula-Python-Dados-/blob/main/Semana3/Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Aula 1

In [ ]:
nome_cliente = "Welington"
idade_cliente = 30
score_ia = 0.98
print(score_ia)

0.98


In [ ]:
nome: str = 'junio'
idade: int = 25
score: float = 1.5
flag: bool = False
print(flag)

False


In [ ]:
texto_sujo = "   MaCHinE LeARning   "

texto_limpo = texto_sujo.strip() # Remove espaços no início e fim
texto_minusculo = texto_limpo.lower() # Tudo minúsculo
texto_maiusculo = texto_limpo.upper() # Tudo maiúsculo
texto_dividido = texto_limpo.split(" ") # Corta o texto onde tem espaço

print(texto_minusculo) # machine learning

machine learning


In [ ]:
print(idade_cliente + idade)
print(nome_cliente,idade_cliente)
print(120/45)
print(120//45)
print(2**10)

55
Welington 30
2.6666666666666665
2
1024


In [ ]:
# Lista de idades (Vetor)
idades = [18, 25, 40, 32]

# Acessando o primeiro item (Índice 0)
print(idades[0])

# Adicionando um dado novo
idades.append(50)

18


In [ ]:
notas = [7.5, 8.0, 9.5]

notas.append(10.0)    # Adiciona no final
notas.insert(0, 5.0)  # Insere na posição zero
notas.pop()           # Remove o último item
notas.sort()          # Ordena do menor para o maior

print(notas)

[5.0, 7.5, 8.0, 9.5]


In [ ]:
# Tupla (Imutável)
coordenadas = (-23.5505, -46.6333)

# Set (Elimina duplicatas automaticamente)
cpfs_compradores = {"111", "222", "111", "333"}
print(cpfs_compradores) # Mostra apenas: {'111', '222', '333'}
print(coordenadas)

{'333', '222', '111'}
(-23.5505, -46.6333)


In [ ]:
aluno = {
    "nome": "Carlos",
    "curso": "Machine Learning",
    "nota_final": 9.5,
    "coordenadass": (-26, -45),
    "endereco" : {
        "rua": "Rua das Flores",
        "numero": 123
    }
}
print(aluno["endereco"])

{'rua': 'Rua das Flores', 'numero': 123}


## Aula 2

In [ ]:
ativo = True
if ativo:
    print("Ativo")
else:
    print("Inativo")

Ativo


In [ ]:
if ativo == False:
    print("Ativo")
else:
    print("Inativo")

Inativo


In [ ]:
inativo = False
if (ativo | inativo):
    print("Ativo")
else:
    print("Inativo")


inativo = False
if (ativo & inativo):
    print("Ativo")
else:
    print("Inativo")

Ativo
Inativo


In [ ]:
a = 10
b = 20
if a > 11 or b > 19:
    print("or sim")
else:
    print("or não")

if a > 11 | b > 19:
    print("| sim")
else:
    print("| não ")

if a < 11 and b > 19:
    print("and sim")
else:
    print("and não")

if a < 11 & b > 19:
    print("& sim")
else:
    print("& não ")

if b > 19 & a < 9:
    print("& sim")
else:
    print("& não ")

or sim
| não 
and sim
& não 
& sim


In [ ]:
categorias_validas = ["Eletrônicos", "Móveis", "Roupas"]
busca = "Móveis"

# Verifica se existe na lista
print(busca in categorias_validas) # Retorna True

# Verifica se uma palavra está numa frase
frase = "Erro no servidor de banco de dados"
print("Erro" in frase) # Retorna True

True
True


In [ ]:
score = 750

if score >= 800:
    print("Crédito Premium")
elif score >= 600:
    print("Crédito Padrão")
else:
    print("Crédito Negado")

Crédito Padrão


In [ ]:
valor_venda = 250.0

if valor_venda > 200.0:
    print("Ganhou Frete Grátis!")
else:
    print("Frete: R$ 15,00")

Ganhou Frete Grátis!


In [ ]:
a='A'
if a == 65:
  print('Eh')
else:
  print('Nao eh')

Nao eh


In [ ]:
numero_digitado = "A" # Deveria ser um número!

try:
    soma = int(numero_digitado) + 10
    print(soma)
except ValueError:
    print("ERRO DE DADOS: O valor fornecido não é um número válido.")

ERRO DE DADOS: O valor fornecido não é um número válido.


In [ ]:
def saudar_aluno(nome="Visitante"):
    return f"Bem-vindo, {nome}!"

print(saudar_aluno("Welington")) # Bem-vindo, Welington!
print(saudar_aluno())            # Bem-vindo, Visitante!

Bem-vindo, Welington!
Bem-vindo, Visitante!


In [ ]:
def calcular_imc(peso, altura):
    return peso / (altura ** 2)

meu_imc = calcular_imc(80, 1.80)

print(f"Meu IMC é: {meu_imc:.2f}")


def definicao_imc(meu_imc):
  if meu_imc < 18.5:
    print("Abaixo do peso")
  elif meu_imc < 24.9:
    print("Peso normal")
  elif meu_imc < 29.9:
    print("Sobrepeso")
  else:
    print("Obesidade")

definicao_imc(meu_imc)

Meu IMC é: 24.69
Peso normal


In [ ]:
def somar(a, b):
    resultado = a + b
    return resultado # A função retorna o valor de 'resultado'

# Chamando a função e armazenando o valor retornado em uma variável
soma_total = somar(5, 3)

# Usando o valor retornado
print(f"A soma é: {soma_total}")

# Podemos usar o valor retornado em outras operações
multiplicacao = soma_total * 2
print(f"O dobro da soma é: {multiplicacao}")

A soma é: 8
O dobro da soma é: 16


## Aula 3

In [ ]:
vendas = [100, 500, 150, 800]

for valor in vendas:
    if valor > 300:
        print(f"Venda de R${valor}: Meta Batida!")

Venda de R$500: Meta Batida!
Venda de R$800: Meta Batida!


In [ ]:
# Repete 5 vezes (de 0 a 4)
for i in range(5):
    print(f"Lendo linha {i} do banco de dados...")

Lendo linha 0 do banco de dados...
Lendo linha 1 do banco de dados...
Lendo linha 2 do banco de dados...
Lendo linha 3 do banco de dados...
Lendo linha 4 do banco de dados...


In [2]:
contagem = 0
while contagem < 5:
    print(f"Número: {contagem}")
    contagem += 1


Número: 0
Número: 1
Número: 2
Número: 3
Número: 4


In [ ]:
for temp in [20, 25, 999, 30]: # 999 é um erro do sensor!
    if temp == 999:
        print("Dado corrompido, pulando...")
        continue # Ignora o 999 e vai para o 30

    print(f"Processando temperatura: {temp}")

Processando temperatura: 20
Processando temperatura: 25
Dado corrompido, pulando...
Processando temperatura: 30


In [ ]:
condicao = 0
while True:
  print("Contagem",condicao)
  if condicao == 10:
    break;
  condicao += 1

Contagem 0
Contagem 1
Contagem 2
Contagem 3
Contagem 4
Contagem 5
Contagem 6
Contagem 7
Contagem 8
Contagem 9
Contagem 10


In [ ]:
frutas = ["maçã", "banana", "cereja"]

for fruta in frutas:
    print(f"Eu gosto de {fruta}.")

Eu gosto de maçã.
Eu gosto de banana.
Eu gosto de cereja.


In [6]:
precos = [100, 200, 300]

# Forma tradicional:
# precos_com_taxa = []
# for p in precos: precos_com_taxa.append(p * 1.1)

# Forma Pythonic (List Comprehension):
precos_com_taxa = [p * 1.25 for p in precos]

print(precos_com_taxa)

[125.0, 250.0, 375.0]


In [11]:
import math
import random

print(math.fsum([1, 2])) # Soma
print(math.sqrt(64)) # Raiz quadrada
print(random.randint(1, 10)) # Número aleatório

3.0
8.0
4


In [13]:
import datetime
from datetime import timezone, timedelta

# Define o fuso horário de Brasília (UTC-3)
brazil_timezone = timezone(timedelta(hours=-3))
print(datetime.datetime.now())
# Obtém a data e hora atuais no fuso horário de Brasília
print(datetime.datetime.now(brazil_timezone))

2026-04-30 23:30:00.540521
2026-04-30 20:30:00.540655-03:00


In [14]:
import numpy as np

# Criando um Array (Vetor Matemático)
vetor = np.array([1, 2, 3, 4])

# Criando uma Matriz (2 linhas e 2 colunas)
matriz = np.array([[1, 2], [3, 4]])
print(vetor)
print(matriz)

[1 2 3 4]
[[1 2]
 [3 4]]


In [16]:
import numpy as np

lista_comum = [10, 20, 30]
print(lista_comum * 2) # ERRO LÓGICO! Ele vai duplicar a lista: [10, 20, 30, 10, 20, 30]

vetor_ia = np.array([[10, 20, 30]])
print(vetor_ia * 2) # SUCESSO! Ele multiplica os números: [20, 40, 60]

[10, 20, 30, 10, 20, 30]
[[20 40 60]]
